### ISSUE TITLE
please backport fix for Disable audio_thread_priority default features

### ISSUE THREAD

**Issue by stefson** [mozilla/audioipc#157]
hi there, 

there is a linking error when compiling firefox without dbus support, and I believe that this is the place to ask the fix to be backported so that it will be backported automatically into the firefox source code tree: 

https://github.com/kinetiknz/audioipc/pull/5/

for more information on the bug, see https://bugzilla.mozilla.org/show_bug.cgi?id=1773336

thank you

**Comment by kinetiknz** [comment]
Sorry about the delay! I'll be landing this fix along with a number of other changes in the next few days.

**Comment by stefson** [comment]
no worries, as long as its queued to be fixed! :-) 

affected are: 103.0 stable, 104.0 beta and 105.0 nightly

**Comment by kinetiknz** [comment]
It'll land via https://bugzilla.mozilla.org/show_bug.cgi?id=1781993, so I'll close this issue.

**Comment by stefson** [comment]
@kinetiknz thanks for the update, I just noticed there are many fixes for `third_party/rust/audioipc2` and none for `third_party/rust/audioipc` in that mozilla pull request?

**Comment by kinetiknz** [comment]
Thanks, I've backported the fix to the old branch and it'll land via https://bugzilla.mozilla.org/show_bug.cgi?id=1782147 shortly.
